source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'SwiftCubicSplineExample', :exclusive => true do
  pod "SwiftCubicSpline", :path => "../"
end

target 'SwiftCubicSplineExampleTests', :exclusive => true do
  pod "SwiftCubicSpline", :path => "../"

  
end
