# references:
# * http://www.objc.io/issue-6/travis-ci.html
# * https://github.com/supermarin/xcpretty#usage

osx_image: xcode11.3
language: swift
# cache: cocoapods
# podfile: Example/Podfile
# before_install:
# - gem install cocoapods # Since Travis is not always on latest version
# - pod install --project-directory=Example
install:
  - gem install xcpretty --no-document --quiet
script:
  - set -o pipefail && xcodebuild test -workspace Example/SwiftCubicSplineExample.xcworkspace -scheme SwiftCubicSplineExample -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO | xcpretty -c
  - pod lib lint --quick
